version: "3.7"

services:
  geofind:
    image: posixpascal/geofind
    container_name: geofind
    restart: always
    ports:
      - 3001:3001

  redis:
    image: "redis:alpine"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
